- run: python main.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: upload
          path: swim.png

      - name: Upload FPL
        uses: actions/upload-artifact@v4
        with:
          name: upload-fpl
          path: fpl_page.html

      - name: Upload Notification
        uses: actions/upload-artifact@v4
        with:
          name: notification-html
          path: notification_page.html
